### ISSUE TITLE
Self-build tesseract-core-simd.wasm.js is different with released js file

### ISSUE THREAD

**Issue by wanghongjuan** [naptha/tesseract.js-core#27]
Hi guys,

I'm trying to build the file `tesseract-core.wasm.js` by myself with tag v2.2.0, but the generated file is different with this report provided. Different wasm content, different file size.

Build Environment:
OS: Ubuntu 20.04
Branch: tag v2.2.0
Follow this [README](https://github.com/naptha/tesseract.js-core/blob/v2.2.0/README.md#contribution) to build the file.

Attach is the build log and self-build js file.
[build.log](https://github.com/naptha/tesseract.js-core/files/9926925/build.log)
[self-build-tesseract-core.wasm.js.txt](https://github.com/naptha/tesseract.js-core/files/9947569/self-build-tesseract-core.wasm.js.txt)

**Comment by Balearica** [comment]
Could the branch tag or file name you mention be a typo?  `tesseract-core-simd.wasm.js` was not created until version 3.

**Comment by wanghongjuan** [comment]
Oops, correct the file name, it should be `tesseract-core.wasm.js`.

**Comment by Balearica** [comment]
Thanks for clarifying.  This probably will not get addressed, as v2 is now multiple major releases old, and the maintainer who created it is no longer active.  If you update to v3 or v4 (which I compiled) and have a similar issue I will assist.

**Comment by Balearica** [comment]
Closing as this appears to be resolved with the current version.
